### ISSUE TITLE
Idea: Easy-Flows to Node-RED

### ISSUE THREAD

**Issue by regicsolutions** [redhat-developer/parodos#10]
Just wanted to throw an idea out there regarding workflow options given it looks like the usage of Easy Flows is still in a exploratory phase.

[Node-RED](https://nodered.org/) is a open-source tool for wiring together APIs and services in interesting ways. It provides a browser-based editor that makes it easy to wire together flows using the wide range of nodes that can be deployed to its runtime in a single-click. There is also a [OpenShift Operator](https://kazuhitoyokoi.medium.com/how-to-use-node-red-operator-on-redhat-openshift-e5a516de1e17) available as well.

The project has been around for 10 years, backed by IBM and there are currently over [4000](https://flows.nodered.org/) nodes and flows available that can be used for just about any use case.

[Documention](https://nodered.org/docs/user-guide/runtime/embedding)

Example Interesting Nodes: 
[aws-nodes](https://flows.nodered.org/node/node-red-contrib-aws)
[azure-nodes](https://github.com/Azure/node-red-contrib-azure)
[google-cloud-nodes](https://github.com/GoogleCloudPlatform/google-cloud)
[jenkins-nodes](https://flows.nodered.org/node/node-red-contrib-jenkins)

**Comment by lshannon** [comment]
The goal is to be able to hook up any workflow framework under the covers, provided that meets our contracts. So another java based workflow library could be put in place. 

For Node-RED specifically, this looks to be more of a mature stand-alone product that a Parodos WorkFlowTask could call out too. Example:
- Node-RED contains flows to stand up AWS
- Parodos has a workflow to not only stand up AWS environments, pipelines, permissions for each of the tools (AD entitlements). Some of this can be delegated to Node-RED, others will be tasks/integrations that might be custom to the environment

The user provides code/project that Parodos assesses and an InfrastructureOption (tools/environments/permissions) is provided to the user. The user picks one of them (for example AWS + Pipelines + supporting tools + all permissions).


Under the covers Parodos will make the calls to stand it all up, including to Node-RED (were some of this logic exists). So in short, Node-RED would be a downstream client to Parodos. 

We could build pre-made Parodos InfrastructureWorkFlow tasks that contain everything that is needed to make a call to Node-RED.

Does this make sense?

**Comment by regicsolutions** [comment]
> The goal is to be able to hook up any workflow framework under the covers, provided that meets our contracts. So another java based workflow library could be put in place. 
> 
> 
> 
> For Node-RED specifically, this looks to be more of a mature stand-alone product that a Parodos WorkFlowTask could call out too. Example:
> 
> - Node-RED contains flows to stand up AWS
> 
> - Parodos has a workflow to not only stand up AWS environments, pipelines, permissions for each of the tools (AD entitlements). Some of this can be delegated to Node-RED, others will be tasks/integrations that might be custom to the environment
> 
> 
> 
> The user provides code/project that Parodos assesses and an InfrastructureOption (tools/environments/permissions) is provided to the user. The user picks one of them (for example AWS + Pipelines + supporting tools + all permissions).
> 
> 
> 
> 
> 
> Under the covers Parodos will make the calls to stand it all up, including to Node-RED (were some of this logic exists). So in short, Node-RED would be a downstream client to Parodos. 
> 
> 
> 
> We could build pre-made Parodos InfrastructureWorkFlow tasks that contain everything that is needed to make a call to Node-RED.
> 
> 
> 
> Does this make sense?

Thanks for the detailed response. So you are not looking to limit the usage of a specific workflow tool and Parados will basically have a universal WorkflowAPI that allows you to call different WorkFlowTasks that can be extended to "open-source drivers" which is what [Humanitec](https://humanitec.com/open-source-drivers?_ga=2.2678576.1893404966.1669951901-304673511.1669951901) calls them, am I correct?

Flexibility is always good 🙂 but things can begin to get tricky when you start to come across use-cases that have tasks that have input/output dependencies where you maybe have task-1 that makes use of tool-a that needs to provide a instanceID output to task-2 that's using tool-b.

Node-RED is super extensible and almost limitless given it can be extended by [creating new nodes](https://nodered.org/docs/creating-nodes/)and simply placing them into your palette.Nodes can be published as npm modules or added to the Node-RED Flow Library to make them available to the community.

**Comment by lshannon** [comment]
"but things can begin to get tricky when you start to come across use-cases that have tasks that have input/output dependencies where you maybe have task-1 that makes use of tool-a that needs to provide a instanceID output to task-2 that's using tool-b." <- We have added support for this. Basically certain workflow steps might generate a 'manual task', like an approval, that occurs outside of the Workflow implementation. Data generated by this 'manual task', an approval ID for example, would be needed to complete the remaining of the Parodos WorkFlow tasks. We believe we have a good solution for this and will be open sourcing this enhancement soon. Just working through some user feedback on our implementation
