### ISSUE TITLE
Feature Request: OpenShift Kpt Support

### ISSUE THREAD

**Issue by regicsolutions** [redhat-developer/parodos#6]
It would be great if parodos provided native OpenShift support for [kpt](https://kpt.dev/) as it only supports [GKE](https://kpt.dev/guides/porch-installation?id=prerequisites) out of the box. 

There are currently two active [kpt backstage plugins](https://github.com/GoogleContainerTools/kpt-backstage-plugins/tree/main/plugins) that are worth exploring 😀

**Comment by lshannon** [comment]
We are working to get our first release together by the end of the year. We will review this once that has been completed. I will leave this issue open so it is not forgotten.

**Comment by regicsolutions** [comment]
> We are working to get our first release together by the end of the year. We will review this once that has been completed. I will leave this issue open so it is not forgotten.

Awesome, thanks!
